# Generated by Django 3.1.7 on 2021-04-03 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Noname cat', max_length=250, unique=True)),
                ('state', models.BooleanField(default=True)),
                ('attributes', models.ManyToManyField(to='product.Attributes')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.categories')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Текст')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(blank=True, max_length=15)),
                ('rate', models.FloatField(default=1)),
                ('disp', models.CharField(blank=True, default='y.e.', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Delivery', max_length=350)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_amount', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('full_amount_on_curr', models.FloatField(default=0)),
                ('total_amount_on_curr', models.FloatField(default=0)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('paid', 'Оплачен'), ('processing', 'В обработке'), ('finished', 'Завершен'), ('cancel', 'Отменен')], default='new', max_length=50)),
                ('rate_currency', models.FloatField(default=1)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.currency')),
            ],
            options={
                'permissions': (('change_status', 'Can change status order'),),
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, unique=True)),
                ('type_code', models.CharField(choices=[('fixed', 'Фиксированная'), ('relative', 'Относительная')], default='fixed', max_length=50)),
                ('amount_of_discount', models.FloatField(default=0)),
                ('type_promo', models.CharField(choices=[('onceuse', 'Одноразовые'), ('reusable', 'Многоразовые')], default='reusable', max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('start_promo', models.DateField(blank=True, null=True)),
                ('end_promo', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('fkey_attr', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.attributes')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Noname', max_length=300)),
                ('stock', models.IntegerField(blank=True, default=0, null=True)),
                ('desc', models.TextField(blank=True, default='', null=True)),
                ('vendor_code', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('old_price', models.FloatField(blank=True, default=0, null=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('photo', models.FileField(default=None, null=True, upload_to='')),
                ('attrs', models.ManyToManyField(to='product.ProductAttrs')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('cid', models.ManyToManyField(related_name='category', to='product.Categories')),
                ('comments', models.ManyToManyField(blank=True, to='product.CommentsProduct')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_good', models.IntegerField(default=1)),
                ('title_good', models.CharField(default='Noname', max_length=300)),
                ('cost', models.FloatField(default=1)),
                ('cost_on_curr', models.FloatField(default=1)),
                ('qty', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='product.promocode'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brand',
            name='categories',
            field=models.ManyToManyField(to='product.Categories'),
        ),
    ]
