# Generated by Django 3.1.7 on 2021-05-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsproduct',
            name='diss_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commentsproduct',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
