# Generated by Django 3.1.7 on 2021-04-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='key_words',
            field=models.ManyToManyField(to='product.KeyWords'),
        ),
    ]
