# Generated by Django 3.1.7 on 2021-05-09 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_auto_20210508_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsproduct',
            name='text',
            field=models.TextField(default='text'),
        ),
        migrations.CreateModel(
            name='CommentsReplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='text')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='commentsproduct',
            name='replies',
            field=models.ManyToManyField(blank=True, to='product.CommentsReplies'),
        ),
    ]
