# Generated by Django 3.1.7 on 2021-04-23 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_auto_20210410_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name matrix', max_length=200, verbose_name='Название')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='full_amount_on_curr',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount_on_curr',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cost_on_curr',
        ),
        migrations.AddField(
            model_name='order',
            name='cost_of_delivery',
            field=models.FloatField(default=0, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.delivery', verbose_name='Способ доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Было ли списание средств.'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='type_product',
            field=models.CharField(choices=[('material', 'Материальный'), ('file', 'Файл')], default='material', max_length=100, verbose_name='Тип товара'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_amount',
            field=models.FloatField(default=0, verbose_name='Полная стоимость товаров в у.е.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.promocode', verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='order',
            name='rate_currency',
            field=models.FloatField(default=1, verbose_name='Курс валюты в момент заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('paid', 'Оплачен'), ('finished', 'Завершен'), ('cancel', 'Отменен')], default='new', max_length=50, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(default=0, verbose_name='Сумма к оплате в у.е.'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubEditPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceMatrixItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField(default=0, verbose_name='От')),
                ('max_value', models.FloatField(default=0, verbose_name='До')),
                ('type_item', models.CharField(choices=[('relative', 'В процентах'), ('fixed', 'Фиксированная')], default='fixed', max_length=50, verbose_name='Тип')),
                ('value', models.FloatField(default=0, verbose_name='Значение')),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.pricematrix')),
            ],
        ),
        migrations.CreateModel(
            name='FileTelegram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_file', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1, verbose_name='Количество')),
                ('price', models.FloatField(verbose_name='Стоимость за ед.')),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'permissions': (('show_all_baskets', 'Просматривать корзины других пользователей'),),
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='matrix',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.pricematrix'),
        ),
    ]
