# Generated by Django 3.1.7 on 2021-05-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210507_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='presentation_images',
            field=models.ManyToManyField(blank=True, to='product.PresentationImages'),
        ),
    ]
