# Generated by Django 3.1.7 on 2021-05-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210507_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationimages',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='presentations'),
        ),
    ]
