# Generated by Django 3.1.7 on 2021-04-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210423_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file_digit',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Файл (при тип товара - Файл)'),
        ),
    ]
