# Generated by Django 3.1.7 on 2021-04-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210424_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattrs',
            name='value',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
