# Generated by Django 3.1.7 on 2021-05-09 12:57

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210509_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='photo',
            field=models.ImageField(blank=True, default='default-logo.img', null=True, upload_to=product.models.file_path),
        ),
        migrations.AlterField(
            model_name='categories',
            name='photo',
            field=models.ImageField(blank=True, default='category_img.jpeg', null=True, upload_to=product.models.file_path),
        ),
        migrations.AlterField(
            model_name='presentationimages',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=product.models.file_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(blank=True, default='img.jpeg', null=True, upload_to=product.models.file_path),
        ),
    ]
