# Generated by Django 3.1.7 on 2021-04-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210424_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='title',
            field=models.CharField(default='title', max_length=200),
        ),
    ]
