# Generated by Django 3.1.7 on 2021-05-12 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0005_auto_20210509_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost_of_delivery',
            field=models.FloatField(default=0, verbose_name='Cost of delivery'),
        ),
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courier', to=settings.AUTH_USER_MODEL, verbose_name='Courier'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.currency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_department',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Shipping address information.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.delivery', verbose_name='Delivery method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_amount',
            field=models.FloatField(default=0, verbose_name='Full price of products in standard units'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Delivery address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Was the funds debited.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Comment on the order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.promocode', verbose_name='Promocode'),
        ),
        migrations.AlterField(
            model_name='order',
            name='rate_currency',
            field=models.FloatField(default=1, verbose_name='Currency rate at the time of order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('paid', 'Paid'), ('finished', 'Finished'), ('cancel', 'Canceled')], default='new', max_length=50, verbose_name='Order status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(default=0, verbose_name='Amount to pay in standard units'),
        ),
    ]
