# Generated by Django 3.1.7 on 2021-04-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_attributes_title'),
        ('product', '0004_product_file_digit'),
    ]

    operations = [
    ]
