# Generated by Django 3.1.7 on 2021-04-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_merge_20210424_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributes',
            name='title',
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productattrs',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
