# Generated by Django 3.1.7 on 2021-05-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210512_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='type_code',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('relative', 'Relative')], default='fixed', max_length=50),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='type_promo',
            field=models.CharField(choices=[('onceuse', 'Disposable'), ('reusable', 'Reusable')], default='reusable', max_length=50),
        ),
    ]
