# Generated by Django 3.1.7 on 2021-04-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210424_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='title',
            field=models.CharField(default='title', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productattrs',
            name='value',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
