# Generated by Django 3.1.7 on 2021-04-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210424_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('discount_percentage', models.FloatField(default=0.0)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, to='product.Categories')),
                ('products', models.ManyToManyField(blank=True, to='product.Product')),
            ],
        ),
    ]
