# Generated by Django 3.1.7 on 2021-04-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_promotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='date_end',
            field=models.DateTimeField(),
        ),
    ]
