# Generated by Django 3.1.7 on 2021-04-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210428_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='task_id',
            field=models.TextField(default='', editable=False),
        ),
    ]
