# Generated by Django 3.1.7 on 2021-04-28 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_promotions_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotions',
            name='task_id',
        ),
        migrations.CreateModel(
            name='PromotionsTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.TextField(default='', editable=False)),
                ('promotion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.promotions')),
            ],
        ),
    ]
