# Generated by Django 3.1.7 on 2021-04-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210428_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionstasks',
            name='task_id',
            field=models.TextField(default=''),
        ),
    ]
