# Generated by Django 3.1.7 on 2021-04-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210428_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='image',
            field=models.ImageField(blank=True, default='promotion.png', upload_to=''),
        ),
    ]
