# Generated by Django 3.1.7 on 2021-04-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_promotions_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionstasks',
            name='task_id',
        ),
        migrations.AddField(
            model_name='promotionstasks',
            name='task_end_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='promotionstasks',
            name='task_start_id',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='image',
            field=models.ImageField(blank=True, default='promotion_img.jpeg', upload_to=''),
        ),
    ]
