# Generated by Django 3.1.7 on 2021-05-06 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0015_auto_20210428_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCitiesNP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('city_ua', models.CharField(blank=True, max_length=150, null=True)),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('region_ua', models.CharField(blank=True, max_length=200, null=True)),
                ('city_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('cityID', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'permissions': (('show_all_wishlist', 'Просматривать список желаний других пользователей'),)},
        ),
        migrations.AddField(
            model_name='delivery',
            name='type_delivery',
            field=models.CharField(choices=[('normal', 'Обычный'), ('np', 'NovaPoshta')], default='normal', max_length=50, verbose_name='Тип (для сторонних интеграций)'),
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courier', to=settings.AUTH_USER_MODEL, verbose_name='Курьер'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_department',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Информация об адресе доставки.'),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_recommend',
            field=models.BooleanField(default=False, verbose_name='Рекомендовать'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
        migrations.CreateModel(
            name='SubActivateProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RatingProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_rating', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_product', to='product.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryWarehousesNP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitekey', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=250)),
                ('description_ru', models.CharField(blank=True, default='', max_length=250)),
                ('short_address', models.CharField(blank=True, default='', max_length=250)),
                ('short_address_ru', models.CharField(blank=True, default='', max_length=250)),
                ('ref_warehouse', models.CharField(blank=True, default='', max_length=250)),
                ('number_warehouse', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.deliverycitiesnp')),
            ],
        ),
    ]
