# Generated by Django 3.1.7 on 2021-05-07 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210507_1834'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.brand'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_tg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_email',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_promo', models.BooleanField(default=False, verbose_name='Акции')),
                ('is_answer_support', models.BooleanField(default=False, verbose_name='Уведомления об ответе службы поддержки')),
                ('is_create_order', models.BooleanField(default=False, verbose_name='Офорлмение заказа')),
                ('is_get_digit_file', models.BooleanField(default=False, verbose_name='Получать цифровые файлы с заказа')),
                ('is_authorization', models.BooleanField(default=False, verbose_name='Успешной авторизации в аккаунт')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
