# Generated by Django 3.1.7 on 2021-04-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210423_1421'),
        ('accounts', '0002_customuser_brand'),
    ]

    operations = [
    ]
