# Generated by Django 3.1.7 on 2021-04-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20210424_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='brand',
        ),
    ]
