# Generated by Django 3.1.7 on 2021-04-24 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210424_1433'),
        ('accounts', '0004_remove_customuser_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.brand'),
        ),
    ]
