# Generated by Django 3.1.7 on 2021-05-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210509_1257'),
        ('accounts', '0004_auto_20210508_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='liked_comments',
            field=models.ManyToManyField(blank=True, to='product.CommentsProduct'),
        ),
    ]
