# Generated by Django 3.1.7 on 2021-05-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210509_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='is_answer_support',
            field=models.BooleanField(default=False, verbose_name='Support response notifications'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='is_authorization',
            field=models.BooleanField(default=False, verbose_name='Successful login to your account'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='is_create_order',
            field=models.BooleanField(default=False, verbose_name='Checkout'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='is_get_digit_file',
            field=models.BooleanField(default=False, verbose_name='Receive digital files from order'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='is_promo',
            field=models.BooleanField(default=False, verbose_name='Promotions'),
        ),
    ]
